apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/n4rm0/demo-k8s:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/n4rm0/demo-k8s:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: demo-k8s
        chartPath: charts/demo-k8s
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/n4rm0/demo-k8s"
          image.tag: "{{.DIGEST_HEX}}"
